server:
  port: 8781

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-server
  redis:
    database: 0
    host: 192.168.52.128
    port: 6379
    timeout: 2000
  #zipkin服务所在地址
  zipkin:
    base-url: http://192.168.52.128:9411/
  #配置服务采样百分比,配置为1就是武全部请求进行抽样
  sleuth:
    sampler:
      probability: 1

#设置超时时间，一般设置不能超过2秒
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
        #开启feign支持hystrix
  hystrix:
    enabled: true

#将hystrix的超时时间禁用,建议不要使用
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#设置超时时间为4S.该请求超时时间的优先级在feign之上
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#配置actuator默认暴露的那些端点，配置暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
env: dev
branch: master
